[project]
name = "team-nova-codebase-genius"
version = "0.1.0"
description = "Automated documentation generator for Python GitHub repositories, built with Jac."
entry-point = "main.jac"

[dependencies]
requests = "*"
GitPython = "*"
pathspec = "*"
tree-sitter = "*"
tree_sitter_python = "*"
IPython = "*"
matplotlib = "*"

[byllm.model]
default_model = "gemini/gemini-2.0-flash"
verbose = true
